import { SupportedDatabase, DatabaseConfig, GenerationParams } from './types';

export const DATABASE_CONFIGS: Record<SupportedDatabase, DatabaseConfig> = {
  h2: {
    driverGroupId: 'com.h2database',
    driverArtifactId: 'h2',
    dialect: 'org.hibernate.dialect.H2Dialect',
    url: 'jdbc:h2:mem:testdb',
    username: 'sa',
    password: '',
    enableH2Console: true,
  },
  postgresql: {
    driverGroupId: 'org.postgresql',
    driverArtifactId: 'postgresql',
    dialect: 'org.hibernate.dialect.PostgreSQLDialect',
    url: 'jdbc:postgresql://localhost:5432/NOMBRE_BD',
    username: 'TU_USUARIO',
    password: 'TU_CONTRASENA',
    enableH2Console: false,
  },
};

export const validateGenerationParams = (
  database: string,
  groupId: string,
  artifactId: string,
  name?: string,
  description?: string,
  packageName?: string,
  javaVersion?: string
): { params: GenerationParams | null; errors: string[] } => {
  const errors: string[] = [];

  if (database !== 'h2' && database !== 'postgresql') {
    errors.push('Base de datos no soportada. Bases soportadas: h2, postgresql');
  }

  const finalGroupId = groupId || 'com.uml2code';
  if (!/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*$/.test(finalGroupId)) {
    errors.push('Invalid groupId format');
  }

  const finalArtifactId = artifactId || 'demo';
  if (!/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(finalArtifactId)) {
    errors.push('Invalid artifactId format');
  }

  const finalPackageName =
    packageName || `${finalGroupId}.${finalArtifactId.replace(/-/g, '')}`;
  if (!/^[a-z][a-z0-9_]*(\.[a-z0-9_]+)*[a-z0-9_]*$/.test(finalPackageName)) {
    errors.push('Invalid packageName format');
  }

  const finalJavaVersion = javaVersion || '17';
  if (!['17', '21', '23', '25'].includes(finalJavaVersion)) {
    errors.push('Invalid javaVersion. Supported: 17, 21, 23, 25');
  }

  if (errors.length > 0) {
    return { params: null, errors };
  }

  return {
    params: {
      database: database as SupportedDatabase,
      groupId: finalGroupId,
      artifactId: finalArtifactId,
      name: name || finalArtifactId,
      description: description || 'Generated by UML2Code',
      packageName: finalPackageName,
      javaVersion: finalJavaVersion,
    },
    errors,
  };
};

export const getDefaultArtifactId = (diagramName: string): string => {
  if (!diagramName) {
    return 'uml-project';
  }

  const formatted = diagramName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

  return formatted || 'uml-project';
};
