import React, { useState } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Typography,
  Box,
  List,
  ListItem,
  ListItemText,
  CircularProgress,
} from '@mui/material';
import axios from 'axios';
import { AlertType } from '../alert/AlertContext';
import useAlert from '../alert/useAlert';

interface ExportSpringBootDialogProps {
  open: boolean;
  onClose: () => void;
  diagramId: string;
  diagramName?: string;
}

interface PreviewWarning {
  code: string;
  element: string;
  message: string;
}

interface PreviewResponse {
  entityCount: number;
  relationshipCount: number;
  fileCount: number;
  warnings: PreviewWarning[];
}

export default function ExportSpringBootDialog({
  open,
  onClose,
  diagramId,
  diagramName = '',
}: ExportSpringBootDialogProps) {
  const [step, setStep] = useState<1 | 2>(1);
  const [database, setDatabase] = useState<'h2' | 'postgresql'>('h2');
  const [groupId, setGroupId] = useState('com.uml2code');
  const [artifactId, setArtifactId] = useState('');
  const [name, setName] = useState('');
  const [description, setDescription] = useState('Generated by UML2Code');
  const [packageName, setPackageName] = useState('com.uml2code');
  const [javaVersion, setJavaVersion] = useState('17');

  const [isPackageDirty, setIsPackageDirty] = useState(false);
  const [isNameDirty, setIsNameDirty] = useState(false);

  React.useEffect(() => {
    if (open) {
      const defaultArtifactId = diagramName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
      setArtifactId(defaultArtifactId);
      setName(diagramName);
      setPackageName(`com.uml2code${defaultArtifactId ? '.' + defaultArtifactId.replace(/-/g, '') : ''}`);
      setIsPackageDirty(false);
      setIsNameDirty(false);
      setStep(1);
    }
  }, [open, diagramName]);

  React.useEffect(() => {
    if (!isPackageDirty) {
      const cleanArtifact = artifactId.replace(/-/g, '').toLowerCase();
      setPackageName(`${groupId}${cleanArtifact ? '.' + cleanArtifact : ''}`);
    }
    if (!isNameDirty) {
      setName(artifactId);
    }
  }, [groupId, artifactId, isPackageDirty, isNameDirty]);

  const [previewData, setPreviewData] = useState<PreviewResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const { setAlert } = useAlert();

  const handleClose = () => {
    setStep(1);
    onClose();
  };

  const isGroupIdValid = (id: string) => {
    return /^[a-z][a-z0-9_]*(\.[a-z0-9_]+)*[a-z0-9_]*$/.test(id);
  };

  const handlePreview = async () => {
    if (!isGroupIdValid(groupId)) {
      setAlert('El groupId no tiene un formato válido.', AlertType.ERROR);
      return;
    }

    setLoading(true);
    try {
      // The API defines it without parameters but spec says we can pass them as query. Wait, the spec says GET without params in route.
      // But actually preview is GET /api/diagram/:diagramId/export/preview with no params, just returns warnings/counts.
      const response = await axios.get(
        `/api/diagram/${diagramId}/export/preview`
      );
      setPreviewData(response.data);
      setStep(2);
    } catch (e) {
      setAlert('Error al obtener la vista previa.', AlertType.ERROR);
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async () => {
    setLoading(true);
    setAlert('Generando código...', AlertType.INFO);
    try {
      const response = await axios.get(
        `/api/diagram/${diagramId}/export/springboot`,
        {
          params: { 
            database, 
            groupId, 
            artifactId,
            name,
            description,
            packageName,
            javaVersion
          },
          responseType: 'blob',
        }
      );

      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `export-${diagramId}.zip`);
      document.body.appendChild(link);
      link.click();
      link.remove();

      setAlert('Código descargado exitosamente.', AlertType.SUCCESS);
      handleClose();
    } catch (e) {
      setAlert('Error al exportar a Spring Boot.', AlertType.ERROR);
    } finally {
      setLoading(false);
    }
  };

  const groupedWarnings =
    previewData?.warnings.reduce((acc, warning) => {
      if (!acc[warning.element]) {
        acc[warning.element] = [];
      }
      acc[warning.element].push(warning.message);
      return acc;
    }, {} as Record<string, string[]>) || {};

  return (
    <Dialog open={open} onClose={handleClose} maxWidth="sm" fullWidth>
      <DialogTitle>
        {step === 1 ? 'Exportar a Spring Boot' : 'Vista Previa'}
      </DialogTitle>

      <DialogContent dividers>
        {step === 1 ? (
          <Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 2, pt: 1 }}>
            <FormControl fullWidth>
              <InputLabel>Base de Datos</InputLabel>
              <Select
                value={database}
                label="Base de Datos"
                onChange={(e) =>
                  setDatabase(e.target.value as 'h2' | 'postgresql')
                }
              >
                <MenuItem value="h2">H2</MenuItem>
                <MenuItem value="postgresql">PostgreSQL</MenuItem>
              </Select>
            </FormControl>

            <FormControl fullWidth>
              <InputLabel>Java Version</InputLabel>
              <Select
                value={javaVersion}
                label="Java Version"
                onChange={(e) => setJavaVersion(e.target.value)}
              >
                <MenuItem value="17">17</MenuItem>
                <MenuItem value="21">21</MenuItem>
                <MenuItem value="23">23</MenuItem>
                <MenuItem value="25">25</MenuItem>
              </Select>
            </FormControl>

            <TextField
              label="Group ID"
              value={groupId}
              onChange={(e) => {
                setGroupId(e.target.value);
                setIsPackageDirty(false);
              }}
              error={!isGroupIdValid(groupId)}
              helperText={
                !isGroupIdValid(groupId)
                  ? 'Formato invǭlido (ej. com.ejemplo)'
                  : ''
              }
              fullWidth
            />

            <TextField
              label="Artifact ID (Opcional)"
              value={artifactId}
              onChange={(e) => {
                setArtifactId(e.target.value);
                setIsPackageDirty(false);
                setIsNameDirty(false);
              }}
              placeholder="Por defecto se deriva del nombre"
              fullWidth
            />
            
            <TextField
              label="Name"
              value={name}
              onChange={(e) => {
                setName(e.target.value);
                setIsNameDirty(true);
              }}
              fullWidth
            />

            <TextField
              label="Description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              fullWidth
            />

            <TextField
              label="Package Name"
              value={packageName}
              onChange={(e) => {
                setPackageName(e.target.value);
                setIsPackageDirty(true);
              }}
              fullWidth
              sx={{ gridColumn: '1 / span 2' }}
            />

          </Box>
        ) : (
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
            {loading ? (
              <Box display="flex" justifyContent="center" p={3}>
                <CircularProgress />
              </Box>
            ) : previewData ? (
              <>
                <Typography variant="subtitle1" fontWeight="bold">
                  Resumen
                </Typography>
                <Box display="flex" justifyContent="space-around">
                  <Typography>Entidades: {previewData.entityCount}</Typography>
                  <Typography>
                    Relaciones: {previewData.relationshipCount}
                  </Typography>
                  <Typography>Archivos: {previewData.fileCount}</Typography>
                </Box>

                <Typography variant="subtitle1" fontWeight="bold" mt={2}>
                  Advertencias
                </Typography>
                {previewData.warnings.length === 0 ? (
                  <Typography color="success.main">
                    El modelo está limpio.
                  </Typography>
                ) : (
                  <List dense>
                    {Object.entries(groupedWarnings).map(
                      ([element, messages]) => (
                        <ListItem
                          key={element}
                          sx={{
                            display: 'flex',
                            flexDirection: 'column',
                            alignItems: 'flex-start',
                          }}
                        >
                          <Typography fontWeight="bold">{element}:</Typography>
                          <ul style={{ margin: 0, paddingLeft: '20px' }}>
                            {messages.map((msg, i) => (
                              <li key={i}>
                                <Typography variant="body2" color="error.main">
                                  {msg}
                                </Typography>
                              </li>
                            ))}
                          </ul>
                        </ListItem>
                      )
                    )}
                  </List>
                )}
              </>
            ) : null}
          </Box>
        )}
      </DialogContent>

      <DialogActions>
        {step === 1 ? (
          <>
            <Button onClick={handleClose}>Cancelar</Button>
            <Button
              onClick={handlePreview}
              variant="contained"
              disabled={!isGroupIdValid(groupId) || loading}
            >
              {loading ? <CircularProgress size={24} /> : 'Continuar'}
            </Button>
          </>
        ) : (
          <>
            <Button onClick={() => setStep(1)} disabled={loading}>
              Atrás
            </Button>
            <Button
              onClick={handleDownload}
              variant="contained"
              color="primary"
              disabled={loading}
            >
              {loading ? <CircularProgress size={24} /> : 'Descargar'}
            </Button>
          </>
        )}
      </DialogActions>
    </Dialog>
  );
}
