import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';
import fs from 'fs';
import path from 'path';
import { DiagramModel } from '../../src/models/diagram.model.js';
import { EntityModel } from '../../src/models/entity.model.js';
import { RelationshipModel } from '../../src/models/relationship.model.js';
import { generateZip } from '../../src/export/generator.js';
import {
  fixtureEntities,
  fixtureRelationships,
} from '../fixtures/fullDiagram.fixture.js';

describe('CI Physical Zip Generator', () => {
  let mongoServer: MongoMemoryServer;

  beforeAll(async () => {
    mongoServer = await MongoMemoryServer.create();
    await mongoose.connect(mongoServer.getUri(), {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    } as mongoose.ConnectOptions);
  });

  afterAll(async () => {
    await mongoose.disconnect();
    await mongoServer.stop();
  });

  it('should generate a physical ZIP file for CI', async () => {
    // Only run this test if CI flag is set, or just run it always because it's fast
    const userId = new mongoose.Types.ObjectId();
    const diagram = await DiagramModel.create({
      name: 'Test Diagram',
      userId,
      isPublic: false,
      collaborators: [],
    });

    const idMap = new Map();
    const dbEntities = fixtureEntities.map((e) => {
      const newId = new mongoose.Types.ObjectId();
      idMap.set(e._id, newId);
      return { ...e, _id: newId, diagramId: diagram._id };
    });

    const dbRelationships = fixtureRelationships.map((r) => ({
      ...r,
      _id: new mongoose.Types.ObjectId(),
      diagramId: diagram._id,
      source: idMap.get(r.source),
      target: idMap.get(r.target),
    }));

    await EntityModel.insertMany(dbEntities);
    await RelationshipModel.insertMany(dbRelationships);

    const { stream, artifactId } = await generateZip(diagram._id.toString(), {
      database: 'h2',
      groupId: 'com.uml2code.test',
      artifactId: 'generated-project',
      name: 'generated-project',
      description: 'Generated by UML2Code',
      packageName: 'com.uml2code.test.generatedproject',
      javaVersion: '17',
    });

    const outPath = path.resolve(__dirname, '../../../generated-project.zip');
    const outStream = fs.createWriteStream(outPath);
    stream.pipe(outStream);

    await new Promise((resolve, reject) => {
      outStream.on('finish', resolve);
      outStream.on('error', reject);
    });

    expect(fs.existsSync(outPath)).toBe(true);
  });
});
