import {
  DATABASE_CONFIGS,
  validateGenerationParams,
  getDefaultArtifactId,
} from '../../src/export/config.js';

describe('Config', () => {
  describe('DATABASE_CONFIGS', () => {
    it('has correct h2 config', () => {
      const config = DATABASE_CONFIGS.h2;
      expect(config.driverGroupId).toBe('com.h2database');
      expect(config.driverArtifactId).toBe('h2');
      expect(config.dialect).toBe('org.hibernate.dialect.H2Dialect');
      expect(config.url).toBe('jdbc:h2:mem:testdb');
      expect(config.username).toBe('sa');
      expect(config.password).toBe('');
      expect(config.enableH2Console).toBe(true);
    });

    it('has correct postgresql config', () => {
      const config = DATABASE_CONFIGS.postgresql;
      expect(config.driverGroupId).toBe('org.postgresql');
      expect(config.driverArtifactId).toBe('postgresql');
      expect(config.dialect).toBe('org.hibernate.dialect.PostgreSQLDialect');
      expect(config.url).toBe('jdbc:postgresql://localhost:5432/NOMBRE_BD');
      expect(config.username).toBe('TU_USUARIO');
      expect(config.password).toBe('TU_CONTRASENA');
      expect(config.enableH2Console).toBe(false);
    });
  });

  describe('validateGenerationParams', () => {
    it('validates h2 params correctly', () => {
      const result = validateGenerationParams(
        'h2',
        'com.example',
        'my-project'
      );
      expect(result.errors).toHaveLength(0);
      expect(result.params).toEqual({
        database: 'h2',
        groupId: 'com.example',
        artifactId: 'my-project',
        name: 'my-project',
        description: 'Generated by UML2Code',
        packageName: 'com.example.myproject',
        javaVersion: '17',
      });
    });

    it('validates postgresql params correctly', () => {
      const result = validateGenerationParams(
        'postgresql',
        'com.example',
        'my-project'
      );
      expect(result.errors).toHaveLength(0);
      expect(result.params).toEqual({
        database: 'postgresql',
        groupId: 'com.example',
        artifactId: 'my-project',
        name: 'my-project',
        description: 'Generated by UML2Code',
        packageName: 'com.example.myproject',
        javaVersion: '17',
      });
    });

    it('returns error for invalid database', () => {
      const result = validateGenerationParams(
        'mysql',
        'com.example',
        'my-project'
      );
      expect(result.errors).toContain(
        'Base de datos no soportada. Bases soportadas: h2, postgresql'
      );
      expect(result.params).toBeNull();
    });

    it('returns error for invalid groupId', () => {
      const result = validateGenerationParams('h2', 'com.UPPER', 'my-project');
      expect(result.errors.length).toBeGreaterThan(0);
      expect(result.params).toBeNull();
    });

    it('returns error for invalid artifactId', () => {
      const result = validateGenerationParams(
        'h2',
        'com.example',
        'My Project'
      );
      expect(result.errors.length).toBeGreaterThan(0);
      expect(result.params).toBeNull();
    });

    it('uses default groupId if empty', () => {
      const result = validateGenerationParams('h2', '', 'my-project');
      expect(result.errors).toHaveLength(0);
      expect(result.params?.groupId).toBe('com.uml2code');
    });

    it('allows empty artifactId', () => {
      const result = validateGenerationParams('h2', 'com.example', '');
      expect(result.errors).toHaveLength(0);
      expect(result.params?.artifactId).toBe('demo');
    });
  });

  describe('getDefaultArtifactId', () => {
    it('converts diagram name to kebab-case', () => {
      expect(getDefaultArtifactId('My Cool Project')).toBe('my-cool-project');
    });

    it('returns default if empty', () => {
      expect(getDefaultArtifactId('')).toBe('uml-project');
    });

    it('handles non-alphanumeric characters', () => {
      expect(getDefaultArtifactId('Project! @# Name')).toBe('project-name');
    });
  });
});
