import { MongoMemoryServer } from 'mongodb-memory-server';
import mongoose, { ConnectOptions } from 'mongoose';
import archiver from 'archiver';
import { DiagramModel } from '../../src/models/diagram.model.js';
import { EntityModel } from '../../src/models/entity.model.js';
import { RelationshipModel } from '../../src/models/relationship.model.js';
import { generatePreview, generateZip } from '../../src/export/generator.js';
import {
  fixtureEntities,
  fixtureRelationships,
} from '../fixtures/fullDiagram.fixture.js';

jest.mock('archiver', () => {
  const mockAppend = jest.fn();
  const mockFinalize = jest.fn();
  const mockPipe = jest.fn();

  return {
    __esModule: true,
    default: jest.fn().mockImplementation(() => ({
      pipe: mockPipe,
      append: mockAppend,
      finalize: mockFinalize,
    })),
  };
});

let mongoServer: MongoMemoryServer;

beforeAll(async () => {
  mongoServer = await MongoMemoryServer.create();
  const mongoUri = mongoServer.getUri();
  await mongoose.connect(mongoUri, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  } as ConnectOptions);
});

afterAll(async () => {
  await mongoose.disconnect();
  await mongoServer.stop();
});

describe('Generator E2E Acceptance Test', () => {
  let diagramId: mongoose.Types.ObjectId;
  let userId: mongoose.Types.ObjectId;

  beforeEach(async () => {
    await DiagramModel.deleteMany({});
    await EntityModel.deleteMany({});
    await RelationshipModel.deleteMany({});
    jest.clearAllMocks();

    userId = new mongoose.Types.ObjectId();
    const diagram = await DiagramModel.create({
      name: 'Hotel System',
      userId,
      isPublic: false,
      collaborators: [],
    });
    diagramId = diagram._id;

    // Map string IDs from fixture to real ObjectIds
    const idMap = new Map<string, mongoose.Types.ObjectId>();

    const dbEntities = fixtureEntities.map((e) => {
      const newId = new mongoose.Types.ObjectId();
      idMap.set(e._id, newId);
      return { ...e, _id: newId, diagramId };
    });

    const dbRelationships = fixtureRelationships.map((r) => {
      const newId = new mongoose.Types.ObjectId();
      return {
        ...r,
        _id: newId,
        diagramId,
        source: idMap.get(r.source) || new mongoose.Types.ObjectId(),
        target: idMap.get(r.target) || new mongoose.Types.ObjectId(),
      };
    });

    await EntityModel.insertMany(dbEntities);
    await RelationshipModel.insertMany(dbRelationships);
  });

  it('should generate a preview with correct counts and warnings', async () => {
    const preview = await generatePreview(diagramId.toString());

    expect(preview.entityCount).toBe(9);
    expect(preview.relationshipCount).toBe(7);
    // 8 base files + (5 * 6 regular classes) + 1 abstract class + 1 interface + 1 enum = 8 + 30 + 1 + 1 + 1 = 41 files
    expect(preview.fileCount).toBe(48);

    // We expect some warnings based on our fixture (Dependency mapped as comment, missing relation, etc.)
    const warningCodes = preview.warnings.map((w) => w.code);
    expect(warningCodes).toContain('DEPENDENCY_MAPPED_AS_COMMENT');
  });

  it('should generate a zip file with expected structure and content', async () => {
    const params = {
      database: 'h2' as const,
      groupId: 'com.hotel',
      artifactId: 'hotel-api',
      name: 'hotel-api',
      description: 'Generated by UML2Code',
      packageName: 'com.hotel.hotelapi',
      javaVersion: '17',
    };

    const { artifactId } = await generateZip(diagramId.toString(), params);

    expect(artifactId).toBe('hotel-api');

    // Verify archiver was called properly
    const mockedArchiver = archiver as unknown as jest.Mock;
    expect(mockedArchiver).toHaveBeenCalledWith('zip', { zlib: { level: 9 } });

    const archiverInstance = mockedArchiver.mock.results[0].value;
    expect(archiverInstance.finalize).toHaveBeenCalled();
    expect(archiverInstance.pipe).toHaveBeenCalled();

    const appendCalls = archiverInstance.append.mock.calls;

    // Validate we generated the correct number of files in the ZIP (41 total)
    expect(appendCalls.length).toBe(51);

    // Helper to find a file in the mock calls
    const getFileContent = (pathSuffix: string) => {
      const call = appendCalls.find((c: any) => c[1].name.endsWith(pathSuffix));
      if (!call)
        throw new Error(`File ending with ${pathSuffix} not found in zip`);
      return call[0] as string;
    };

    // 1. Root files
    const pomXml = getFileContent('pom.xml');
    expect(pomXml).toContain('<groupId>com.hotel</groupId>');
    expect(pomXml).toContain('<artifactId>h2</artifactId>');

    // 2. Application properties
    const postmanJson = getFileContent(
      'postman/hotel-api.postman_collection.json'
    );
    expect(postmanJson).toContain('Hotel System - API');
    expect(postmanJson).toContain('baseUrl');
    const applicationProperties = getFileContent('application.properties');
    expect(applicationProperties).toContain(
      'spring.datasource.url=jdbc:h2:mem:testdb'
    );

    // 3. Domain classes (Entities)
    const userClass = getFileContent('model/User.java');
    expect(userClass).toContain('public abstract class User');
    expect(userClass).toContain(
      '@Inheritance(strategy = InheritanceType.SINGLE_TABLE)'
    );

    const guestClass = getFileContent('model/Guest.java');
    expect(guestClass).toContain('public class Guest extends User');
    expect(guestClass).toContain('@DiscriminatorValue("Guest")');
    expect(guestClass).toContain('private List<Reservation> reservations;');

    const reservationClass = getFileContent('model/Reservation.java');
    expect(reservationClass).toContain('public class Reservation');
    expect(reservationClass).toContain('@OneToOne');
    expect(reservationClass).toContain('private Invoice invoice;');
    expect(reservationClass).toContain('@ManyToOne');
    expect(reservationClass).toContain('private Room room;');

    // 4. Interfaces and Enums
    const paymentInterface = getFileContent('model/Payment.java');
    expect(paymentInterface).toContain('public interface Payment');
    expect(paymentInterface).toContain('public boolean process();');

    const roomStatusEnum = getFileContent('model/RoomStatus.java');
    expect(roomStatusEnum).toContain('public enum RoomStatus');
    expect(roomStatusEnum).toContain('AVAILABLE');

    // 5. Repositories, Services, Controllers
    const roomRepo = getFileContent('repository/RoomRepository.java');
    expect(roomRepo).toContain(
      'public interface RoomRepository extends JpaRepository<Room, Long>'
    );

    const roomService = getFileContent('service/RoomService.java');
    expect(roomService).toContain('@Service');
    expect(roomService).toContain(
      'public RoomService(RoomRepository roomRepository)'
    );

    const roomController = getFileContent('controller/RoomController.java');
    expect(roomController).toContain('@RestController');
    expect(roomController).toContain('@RequestMapping("/api/room")');
    expect(roomController).toContain(
      'public RoomDto create(@Valid @RequestBody RoomDto dto)'
    );
  });
});
