import { JavaClass, GenerationParams } from '../../src/export/types.js';
import { generatePostmanCollection } from '../../src/export/templates/postman.template.js';

describe('Postman Collection Generation (C42)', () => {
  let classMap: Map<string, JavaClass>;
  let config: GenerationParams;

  beforeEach(() => {
    config = {
      groupId: 'com.demo',
      artifactId: 'demo-api',
      database: 'h2',
      name: 'postman-test',
      description: 'Generated by UML2Code',
      packageName: 'com.uml2code.test.postman',
      javaVersion: '17',
    };
    classMap = new Map();
  });

  it('T-C42a, T-C42b, T-C42c, T-C42d: generates valid JSON with correct structure and routes', () => {
    const rootClass: JavaClass = {
      className: 'Root',
      tableName: 'root',
      restPath: '/api/root',
      fields: [
        { name: 'id', javaType: 'Long', annotations: [], isId: true },
        { name: 'name', javaType: 'String', annotations: [], isId: false },
      ],
      relationFields: [],
      methods: [],
      implementsInterfaces: [],
      discriminatorAnnotations: [],
      isSubclass: false,
      isAbstract: false,
    };

    classMap.set(rootClass.className, rootClass);

    const result = generatePostmanCollection(
      Array.from(classMap.values()),
      [],
      classMap,
      config,
      'Root API'
    );
    expect(result).toBeDefined();

    const json = JSON.parse(result!.content);
    expect(json.info.schema).toBe(
      'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
    );
    expect(json.item).toHaveLength(2); // Root + Limpieza

    const rootFolder = json.item[0];
    expect(rootFolder.name).toBe('Root');
    expect(rootFolder.item).toHaveLength(4);

    // Check routes and methods
    expect(rootFolder.item[0].request.method).toBe('GET');
    expect(rootFolder.item[0].request.url.raw).toBe('{{baseUrl}}/api/root');
  });

  it('T-C42h: does not generate collection if no concrete classes', () => {
    const result = generatePostmanCollection([], [], classMap, config, 'API');
    expect(result).toBeNull();
  });
});
